spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db-changelog.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 5MB # max single file size
      max-request-size: 20MB # max summary file size
  profiles:
    include: prod
storage:
  location: /tmp/ninja-mirea-clone/storage
