spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tinek-project
    username: test-user
    password: test
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

storage:
  location: /tmp/ninja-mirea-clone/storage