spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db-changelog.xml

storage:
  location: /tmp/ninja-mirea-clone/storage